name: "Platform Feedback Submission"
description: Share your feedback or suggestions to improve our open-source Bitcoin development education platform.
labels: [feedback]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve this plateform with your feedback.
  - type: input
    id: title
    attributes:
      label: Title
      description: Please provide a title for your feedback.
      placeholder: Enter a title for your feedback.
    validations:
      required: true
  - type: textarea
    id: feedback-details
    attributes:
      label: Feedback
      description: Describe in detail the feedback or suggestions you have for the platform.
      placeholder: Enter your feedback here.
    validations:
      required: true
